name: CI - Continuous Integration

on:
  push:
    branches:
      - feature/**
      - develop
  pull_request:
    branches:
      - master
      - main

jobs:
  test:
    name: Run Tests
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '18'
          cache: 'npm'
          cache-dependency-path: src/package-lock.json

      - name: Install dependencies
        working-directory: ./src
        run: npm ci

      - name: Run linter
        working-directory: ./src
        run: npm run lint:check

      - name: Run tests
        working-directory: ./src
        run: npm test

      - name: Run format check
        working-directory: ./src
        run: npm run format:check

  docker-build:
    name: Docker Build Test
    runs-on: ubuntu-latest
    needs: test

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Build Docker image
        working-directory: ./src
        run: docker build -t golden-owl-app:test .

      - name: Test Docker image
        run: |
          docker run -d -p 3000:3000 --name test-container golden-owl-app:test
          sleep 5
          response=$(curl -s http://localhost:3000)
          echo "Response: $response"
          if echo "$response" | grep -q "Welcome warriors to Golden Owl"; then
            echo "✅ Docker container is working correctly!"
            exit 0
          else
            echo "❌ Docker container test failed"
            exit 1
          fi
